services:
  health-dairy-bot:
    build: .
    container_name: health-dairy-bot
    env_file: .env
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./data:/root/data
      - ./logs:/root/logs
      - ./bot.db:/app/bot.db
    restart: always
