services:
  health-dairy-bot:
    build: .
    container_name: health-dairy-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./data:/root/data
      - ./logs:/root/logs
    restart: always
